from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `api` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `path` VARCHAR(100) NOT NULL  COMMENT 'API路径',
    `method` VARCHAR(6) NOT NULL  COMMENT '请求方法',
    `summary` VARCHAR(500) NOT NULL  COMMENT '请求简介',
    `tags` VARCHAR(100) NOT NULL  COMMENT 'API标签',
    KEY `idx_api_created_78d19f` (`created_at`),
    KEY `idx_api_updated_643c8b` (`updated_at`),
    KEY `idx_api_path_9ed611` (`path`),
    KEY `idx_api_method_a46dfb` (`method`),
    KEY `idx_api_summary_400f73` (`summary`),
    KEY `idx_api_tags_04ae27` (`tags`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `auditlog` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL  COMMENT '用户ID',
    `username` VARCHAR(64) NOT NULL  COMMENT '用户名称' DEFAULT '',
    `module` VARCHAR(64) NOT NULL  COMMENT '功能模块' DEFAULT '',
    `summary` VARCHAR(128) NOT NULL  COMMENT '请求描述' DEFAULT '',
    `method` VARCHAR(10) NOT NULL  COMMENT '请求方法' DEFAULT '',
    `path` VARCHAR(255) NOT NULL  COMMENT '请求路径' DEFAULT '',
    `status` INT NOT NULL  COMMENT '状态码' DEFAULT -1,
    `response_time` INT NOT NULL  COMMENT '响应时间(单位ms)' DEFAULT 0,
    `request_args` JSON   COMMENT '请求参数',
    `response_body` JSON   COMMENT '返回数据',
    KEY `idx_auditlog_created_cc33d0` (`created_at`),
    KEY `idx_auditlog_updated_2f871f` (`updated_at`),
    KEY `idx_auditlog_user_id_4b93fa` (`user_id`),
    KEY `idx_auditlog_usernam_b187b3` (`username`),
    KEY `idx_auditlog_module_04058b` (`module`),
    KEY `idx_auditlog_summary_3e27da` (`summary`),
    KEY `idx_auditlog_method_4270a2` (`method`),
    KEY `idx_auditlog_path_b99502` (`path`),
    KEY `idx_auditlog_status_2a72d2` (`status`),
    KEY `idx_auditlog_respons_8caa87` (`response_time`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `dept` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL UNIQUE COMMENT '部门名称',
    `desc` VARCHAR(500)   COMMENT '备注',
    `is_deleted` BOOL NOT NULL  COMMENT '软删除标记' DEFAULT 0,
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    `parent_id` INT NOT NULL  COMMENT '父部门ID' DEFAULT 0,
    KEY `idx_dept_created_4b11cf` (`created_at`),
    KEY `idx_dept_updated_0c0bd1` (`updated_at`),
    KEY `idx_dept_name_c2b9da` (`name`),
    KEY `idx_dept_is_dele_466228` (`is_deleted`),
    KEY `idx_dept_order_ddabe1` (`order`),
    KEY `idx_dept_parent__a71a57` (`parent_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `deptclosure` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `ancestor` INT NOT NULL  COMMENT '父代',
    `descendant` INT NOT NULL  COMMENT '子代',
    `level` INT NOT NULL  COMMENT '深度' DEFAULT 0,
    KEY `idx_deptclosure_created_96f6ef` (`created_at`),
    KEY `idx_deptclosure_updated_41fc08` (`updated_at`),
    KEY `idx_deptclosure_ancesto_fbc4ce` (`ancestor`),
    KEY `idx_deptclosure_descend_2ae8b1` (`descendant`),
    KEY `idx_deptclosure_level_ae16b2` (`level`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `menu` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '菜单名称',
    `remark` JSON   COMMENT '保留字段',
    `menu_type` VARCHAR(7)   COMMENT '菜单类型',
    `icon` VARCHAR(100)   COMMENT '菜单图标',
    `path` VARCHAR(100) NOT NULL  COMMENT '菜单路径',
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    `parent_id` INT NOT NULL  COMMENT '父菜单ID' DEFAULT 0,
    `is_hidden` BOOL NOT NULL  COMMENT '是否隐藏' DEFAULT 0,
    `component` VARCHAR(100) NOT NULL  COMMENT '组件',
    `keepalive` BOOL NOT NULL  COMMENT '存活' DEFAULT 1,
    `redirect` VARCHAR(100)   COMMENT '重定向',
    KEY `idx_menu_created_b6922b` (`created_at`),
    KEY `idx_menu_updated_e6b0a1` (`updated_at`),
    KEY `idx_menu_name_b9b853` (`name`),
    KEY `idx_menu_path_bf95b2` (`path`),
    KEY `idx_menu_order_606068` (`order`),
    KEY `idx_menu_parent__bebd15` (`parent_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `partner_registration` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `register_type` VARCHAR(7) NOT NULL  COMMENT '注册类型' DEFAULT 'channel',
    `company_name` VARCHAR(120) NOT NULL  COMMENT '公司名称',
    `contact_name` VARCHAR(60) NOT NULL  COMMENT '联系人',
    `email` VARCHAR(255) NOT NULL  COMMENT '邮箱',
    `phone` VARCHAR(20) NOT NULL  COMMENT '手机号',
    `username` VARCHAR(255) NOT NULL  COMMENT '用户名',
    `hardware_id` VARCHAR(80)   COMMENT '产品硬件ID',
    `password_hash` VARCHAR(128) NOT NULL  COMMENT '密码哈希',
    `status` VARCHAR(8) NOT NULL  COMMENT 'PENDING: pending\nAPPROVED: approved\nREJECTED: rejected' DEFAULT 'pending',
    `reviewer_id` BIGINT   COMMENT '审核人ID',
    `review_comment` VARCHAR(500)   COMMENT '审核备注',
    `reviewed_at` DATETIME(6)   COMMENT '审核时间',
    KEY `idx_partner_reg_created_b8f4b2` (`created_at`),
    KEY `idx_partner_reg_updated_6d2313` (`updated_at`),
    KEY `idx_partner_reg_registe_288e93` (`register_type`),
    KEY `idx_partner_reg_email_ed1b60` (`email`),
    KEY `idx_partner_reg_phone_7899e6` (`phone`),
    KEY `idx_partner_reg_usernam_879b58` (`username`),
    KEY `idx_partner_reg_hardwar_fd177a` (`hardware_id`),
    KEY `idx_partner_reg_status_6e40d9` (`status`),
    KEY `idx_partner_reg_reviewe_1da842` (`reviewer_id`),
    KEY `idx_partner_reg_reviewe_3e8c07` (`reviewed_at`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL UNIQUE COMMENT '角色名称',
    `desc` VARCHAR(500)   COMMENT '角色描述',
    KEY `idx_role_created_7f5f71` (`created_at`),
    KEY `idx_role_updated_5dd337` (`updated_at`),
    KEY `idx_role_name_e5618b` (`name`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `system_setting` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `site_title` VARCHAR(120) NOT NULL  COMMENT '网站标题' DEFAULT 'Vue FastAPI Admin',
    `site_logo` VARCHAR(500)   COMMENT '网站Logo',
    `allow_partner_register` BOOL NOT NULL  COMMENT '是否开放代理商注册' DEFAULT 1,
    `ticket_attachment_extensions` JSON NOT NULL  COMMENT '工单附件允许上传类型',
    `ticket_project_phases` JSON NOT NULL  COMMENT '工单项目阶段',
    `ticket_categories` JSON NOT NULL  COMMENT '工单分类',
    `ticket_root_causes` JSON NOT NULL  COMMENT '工单问题根因',
    `ticket_description_templates` JSON NOT NULL  COMMENT '工单问题描述模板',
    `role_home_pages` JSON NOT NULL  COMMENT '角色默认首页配置',
    `login_security_enabled` BOOL NOT NULL  COMMENT '是否启用登录安全策略' DEFAULT 1,
    `login_account_ip_fail_limit` INT NOT NULL  COMMENT '账号+IP失败锁定阈值' DEFAULT 5,
    `login_account_ip_lock_minutes` INT NOT NULL  COMMENT '账号+IP锁定时长(分钟)' DEFAULT 60,
    `login_ip_fail_limit` INT NOT NULL  COMMENT 'IP失败锁定阈值' DEFAULT 20,
    `login_ip_lock_minutes` INT NOT NULL  COMMENT 'IP锁定时长(分钟)' DEFAULT 60,
    `login_fail_window_minutes` INT NOT NULL  COMMENT '登录失败统计窗口(分钟)' DEFAULT 60,
    `login_generic_error_enabled` BOOL NOT NULL  COMMENT '是否启用统一登录错误提示' DEFAULT 1,
    `password_min_length` INT NOT NULL  COMMENT '密码最小长度' DEFAULT 8,
    `password_min_category_count` INT NOT NULL  COMMENT '密码最少字符类别数' DEFAULT 2,
    `ticket_mail_notify_statuses` JSON NOT NULL  COMMENT '工单状态触发邮件通知',
    `smtp_host` VARCHAR(120)   COMMENT 'SMTP主机',
    `smtp_port` INT NOT NULL  COMMENT 'SMTP端口' DEFAULT 465,
    `smtp_username` VARCHAR(120)   COMMENT 'SMTP用户名',
    `smtp_password` VARCHAR(200)   COMMENT 'SMTP密码',
    `smtp_sender` VARCHAR(120)   COMMENT '发件邮箱',
    `smtp_sender_name` VARCHAR(120) NOT NULL  COMMENT '发件人名称' DEFAULT '系统通知',
    `smtp_use_tls` BOOL NOT NULL  COMMENT '是否使用TLS' DEFAULT 0,
    `smtp_use_ssl` BOOL NOT NULL  COMMENT '是否使用SSL' DEFAULT 1,
    `email_verify_subject` VARCHAR(200) NOT NULL  COMMENT '验证邮件主题' DEFAULT '代理商注册验证码',
    `email_verify_is_html` BOOL NOT NULL  COMMENT '验证码邮件是否HTML' DEFAULT 1,
    `email_verify_template` LONGTEXT NOT NULL  COMMENT '验证邮件模板',
    `register_review_approve_subject` VARCHAR(200) NOT NULL  COMMENT '注册审核通过邮件主题' DEFAULT '注册审核结果通知',
    `register_review_approve_is_html` BOOL NOT NULL  COMMENT '注册审核通过模板是否HTML' DEFAULT 1,
    `register_review_approve_template` LONGTEXT NOT NULL  COMMENT '注册审核通过邮件模板',
    `register_review_reject_subject` VARCHAR(200) NOT NULL  COMMENT '注册审核驳回邮件主题' DEFAULT '注册审核结果通知',
    `register_review_reject_is_html` BOOL NOT NULL  COMMENT '注册审核驳回模板是否HTML' DEFAULT 1,
    `register_review_reject_template` LONGTEXT NOT NULL  COMMENT '注册审核驳回邮件模板',
    `reset_password_subject` VARCHAR(200) NOT NULL  COMMENT '找回密码验证码邮件主题' DEFAULT '密码重置验证码',
    `reset_password_is_html` BOOL NOT NULL  COMMENT '找回密码验证码模板是否HTML' DEFAULT 0,
    `reset_password_template` LONGTEXT NOT NULL  COMMENT '找回密码验证码邮件模板',
    `admin_reset_password_subject` VARCHAR(200) NOT NULL  COMMENT '管理员重置密码通知邮件主题' DEFAULT '账号密码已重置',
    `admin_reset_password_is_html` BOOL NOT NULL  COMMENT '管理员重置密码通知是否HTML' DEFAULT 0,
    `admin_reset_password_template` LONGTEXT NOT NULL  COMMENT '管理员重置密码通知邮件模板',
    `webdav_enabled` BOOL NOT NULL  COMMENT '是否启用WebDAV' DEFAULT 0,
    `webdav_base_url` VARCHAR(500)   COMMENT 'WebDAV基础地址',
    `webdav_username` VARCHAR(120)   COMMENT 'WebDAV用户名',
    `webdav_password` VARCHAR(255)   COMMENT 'WebDAV密码',
    `webdav_share_default_expire_hours` INT NOT NULL  COMMENT 'WebDAV默认分享有效时长(小时)' DEFAULT 168,
    `webdav_signature_secret` VARCHAR(255)   COMMENT 'WebDAV签名密钥',
    KEY `idx_system_sett_created_ac1169` (`created_at`),
    KEY `idx_system_sett_updated_29637b` (`updated_at`),
    KEY `idx_system_sett_webdav__62c048` (`webdav_enabled`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `ticket` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `ticket_no` VARCHAR(40) NOT NULL UNIQUE COMMENT '工单编号',
    `company_name` VARCHAR(120) NOT NULL  COMMENT '公司名称',
    `contact_name` VARCHAR(60) NOT NULL  COMMENT '联系人',
    `email` VARCHAR(255) NOT NULL  COMMENT '邮箱',
    `phone` VARCHAR(20) NOT NULL  COMMENT '手机号',
    `project_phase` VARCHAR(30) NOT NULL  COMMENT '项目阶段',
    `category` VARCHAR(60) NOT NULL  COMMENT '问题分类',
    `title` VARCHAR(200) NOT NULL  COMMENT '问题标题',
    `description` LONGTEXT NOT NULL  COMMENT '问题描述',
    `status` VARCHAR(15) NOT NULL  COMMENT 'PENDING_REVIEW: pending_review\nCS_REJECTED: cs_rejected\nTECH_PROCESSING: tech_processing\nTECH_REJECTED: tech_rejected\nDONE: done' DEFAULT 'pending_review',
    `submitter_id` BIGINT NOT NULL  COMMENT '提交人ID',
    `reviewer_id` BIGINT   COMMENT '客服审核人ID',
    `tech_id` BIGINT   COMMENT '技术处理人ID',
    `reject_reason` LONGTEXT   COMMENT '驳回原因',
    `root_cause` VARCHAR(120)   COMMENT '问题根因',
    `finished_at` DATETIME(6)   COMMENT '完成时间',
    KEY `idx_ticket_created_ad5b9c` (`created_at`),
    KEY `idx_ticket_updated_7b3bd6` (`updated_at`),
    KEY `idx_ticket_ticket__6ba9b7` (`ticket_no`),
    KEY `idx_ticket_email_58fe0e` (`email`),
    KEY `idx_ticket_phone_5f45c9` (`phone`),
    KEY `idx_ticket_project_33b636` (`project_phase`),
    KEY `idx_ticket_categor_bcdee6` (`category`),
    KEY `idx_ticket_title_fbf4df` (`title`),
    KEY `idx_ticket_status_f3afba` (`status`),
    KEY `idx_ticket_submitt_939eef` (`submitter_id`),
    KEY `idx_ticket_reviewe_7ec11e` (`reviewer_id`),
    KEY `idx_ticket_tech_id_b45445` (`tech_id`),
    KEY `idx_ticket_root_ca_977953` (`root_cause`),
    KEY `idx_ticket_finishe_e7eebf` (`finished_at`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `ticket_action_log` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `ticket_id` BIGINT NOT NULL  COMMENT '工单ID',
    `action` VARCHAR(11) NOT NULL  COMMENT '动作类型',
    `from_status` VARCHAR(15)   COMMENT '变更前状态',
    `to_status` VARCHAR(15) NOT NULL  COMMENT '变更后状态',
    `operator_id` BIGINT NOT NULL  COMMENT '操作人ID',
    `comment` LONGTEXT   COMMENT '备注',
    KEY `idx_ticket_acti_created_a48e62` (`created_at`),
    KEY `idx_ticket_acti_updated_5bed7d` (`updated_at`),
    KEY `idx_ticket_acti_ticket__74bcca` (`ticket_id`),
    KEY `idx_ticket_acti_action_292586` (`action`),
    KEY `idx_ticket_acti_from_st_b02071` (`from_status`),
    KEY `idx_ticket_acti_to_stat_aebbdf` (`to_status`),
    KEY `idx_ticket_acti_operato_827ddd` (`operator_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `ticket_attachment` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `ticket_id` BIGINT   COMMENT '工单ID',
    `origin_name` VARCHAR(255) NOT NULL  COMMENT '原始文件名',
    `file_path` VARCHAR(500) NOT NULL  COMMENT '文件相对路径',
    `file_size` BIGINT NOT NULL  COMMENT '文件大小' DEFAULT 0,
    `mime_type` VARCHAR(100) NOT NULL  COMMENT 'MIME类型' DEFAULT 'application/octet-stream',
    `uploader_id` BIGINT NOT NULL  COMMENT '上传人ID',
    KEY `idx_ticket_atta_created_d4f975` (`created_at`),
    KEY `idx_ticket_atta_updated_b28ad5` (`updated_at`),
    KEY `idx_ticket_atta_ticket__e2b9b6` (`ticket_id`),
    KEY `idx_ticket_atta_uploade_8dddf7` (`uploader_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `username` VARCHAR(255) NOT NULL UNIQUE COMMENT '用户名称',
    `alias` VARCHAR(30)   COMMENT '用户姓名',
    `company_name` VARCHAR(120)   COMMENT '公司名称',
    `hardware_id` VARCHAR(80)  UNIQUE COMMENT '产品硬件ID',
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '邮箱',
    `phone` VARCHAR(20)  UNIQUE COMMENT '电话',
    `password` VARCHAR(128)   COMMENT '密码',
    `is_active` BOOL NOT NULL  COMMENT '是否激活' DEFAULT 1,
    `is_superuser` BOOL NOT NULL  COMMENT '是否为超级管理员' DEFAULT 0,
    `last_login` DATETIME(6)   COMMENT '最后登录时间',
    `dept_id` INT   COMMENT '部门ID',
    KEY `idx_user_created_b19d59` (`created_at`),
    KEY `idx_user_updated_dfdb43` (`updated_at`),
    KEY `idx_user_usernam_9987ab` (`username`),
    KEY `idx_user_alias_6f9868` (`alias`),
    KEY `idx_user_company_501097` (`company_name`),
    KEY `idx_user_hardwar_7b9727` (`hardware_id`),
    KEY `idx_user_email_1b4f1c` (`email`),
    KEY `idx_user_phone_4e3ecc` (`phone`),
    KEY `idx_user_is_acti_83722a` (`is_active`),
    KEY `idx_user_is_supe_b8a218` (`is_superuser`),
    KEY `idx_user_last_lo_af118a` (`last_login`),
    KEY `idx_user_dept_id_d4490b` (`dept_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `webdav_share_link` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `code` VARCHAR(32) NOT NULL UNIQUE COMMENT '分享码',
    `file_path` VARCHAR(1000) NOT NULL  COMMENT '文件路径',
    `file_name` VARCHAR(255) NOT NULL  COMMENT '文件名',
    `expire_time` DATETIME(6) NOT NULL  COMMENT '过期时间',
    `is_active` BOOL NOT NULL  COMMENT '是否生效' DEFAULT 1,
    `created_by` BIGINT NOT NULL  COMMENT '创建人ID',
    KEY `idx_webdav_shar_created_e6cf43` (`created_at`),
    KEY `idx_webdav_shar_updated_8d1ca6` (`updated_at`),
    KEY `idx_webdav_shar_code_9d88b4` (`code`),
    KEY `idx_webdav_shar_expire__1bd4e9` (`expire_time`),
    KEY `idx_webdav_shar_is_acti_95b482` (`is_active`),
    KEY `idx_webdav_shar_created_e61f1c` (`created_by`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role_menu` (
    `role_id` BIGINT NOT NULL,
    `menu_id` BIGINT NOT NULL,
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`menu_id`) REFERENCES `menu` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uidx_role_menu_role_id_90801c` (`role_id`, `menu_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role_api` (
    `role_id` BIGINT NOT NULL,
    `api_id` BIGINT NOT NULL,
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`api_id`) REFERENCES `api` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uidx_role_api_role_id_ba4286` (`role_id`, `api_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `user_role` (
    `user_id` BIGINT NOT NULL,
    `role_id` BIGINT NOT NULL,
    FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uidx_user_role_user_id_d0bad3` (`user_id`, `role_id`)
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
